travis:
  secure:
    BINSTAR_TOKEN: QKp6tErO0ADbNgkglpqgpyYpjWJY6H8DpbYhVrT62b9SURWRya68I8qkBLDKYFjHfsc8IXMmOP9U6IpC1tmDHbc3S9ErzgwKyekBFITXcG8v3fM0NbjJqKogj5wq7qlSuPMUKRvJI9eMSWbXm4R8Bh/erVwTXwoh4d5dxSj0Jy5sTKWd9KYbJnjMlBfilScwAczOQoxVMXfGeyzVqEiZL6lvD1HHUa3jqF4QuWlTo4HYcNMDTnn0hONOH1sD9VR2NwLKnLQhgX3BN0OlB27bU7yPhEUsYAluKTpvzQrOfi/LV0ofm2r358/Wa+QlCitr0qnL1qSS/fn8iGuE63+MkUgGw8wYccFJ/6h0k+CkrCsOMwj8WNkU8gCb2WikAZ9vujXOLFFJbqgXo6TPXuWOOuwttAilO7LgQPBHTe7L0Rse3K8TaRpKpvl6fF62qrpUs43tzWfXqDIOsV9oXWLXxdU+VA3Wfs0l1gphzxZuEm7H9EqdX/+Q+1SeMyxh96nJ6rPptu3t7QcnjXbbXxAqB3axAbCMJAtClskm5xbsr+3Pxpb4eBKNAEjCOx9FrUeJYBUOdf+vjBh3OZ/d4YJSbZQKxySCLhtJz+dF0ecNn9ffA/v+xZ01vrdW5qcCCV1ujuqbsr9lcRKVz0ToqKDMdVH06EIkxHUzwC2OPVYSqDs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
