travis:
  secure:
    BINSTAR_TOKEN: jh3WD9g0YO51W9DIoAxSU+UU5q9zw17jvmQGHWsM8Na5qfI6wy7KXCY3Crw56qIz+XcxCr8knTXt0ljCn16/S2TLIW5VzIggmSrjMwgCx6sD+eN8+BCrSYLpsJ446pn0Zxrk36g7h//g9hmXZMwkEe2gwGlavQF05fG9fPyWmviUOjksQjDB5pc3kNI+W0sUwY9PBlZxg+pu9X+Te3mnHy1OxhQT2iaKgYR+horRPRMpz1yduYw+pDffXLQvCOkmIs03lWO7u0FPMn5sHalZ0kyNKh/fJK7v1D/RKPT7NbaPPUSR8xJW3Zc5mr1qFc6g8+u+RniEy5eWz6Xvd2dsNRhr1YYDkkjYEsO4RbH8Lyw/VSUmZjU1zALuagpL7g3Rfschmu6SWwnxQIPOZ0u14E1IHvrqTY7+1wE0XwhTEDjFD+h4jk8Q0eAxo0d/mFNTHbl79lfKDc2IhmhymU5DkwnJTZlDh6pEKEXKCjkI0xJq17LKTQ1I0a6DpXvS7Eae1axHiWqFueLqYUR8dksKZ4wXznqQGHaiqtFqLs/kuFIgJVhoOaOIwpxXn1v3U1Lw/5KSAClYZYZBilwUJ4YXHs0Rj1tymGslN/dP+XKRMDE6GsADvjlP1ViRh2tN8VgStcoobNCgK7biS9ssnZDZiVNHbuCrnzfvZdUfY/m56Kk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
