travis:
  secure:
    BINSTAR_TOKEN: En0cn5unF8xsNVexGM/143eSltG6SdtH/7BcZ05Xwv1cc+HDAXoYWmSUEu0Gs21yvp49IKADfxxw7QzfZ75V1cZZMRpabbcYKh3YmKIavLmE23HfcD+lTG3SjwKANm37JUhhd4ijauR2fxmP43Je1+1ewT6w3EiNOV73FzpWBYu4ymZ8k51h95lt+qGCpcUPoioKhBsR3mZsgHsEVGKmU1OQLCyoT2RABwhZP0MvfKqrJsIVyhpXdxpEr0aZvqlXSawyf5p84c+y/0hoQFZ1WEWsu67wAvifIuT7eYJFrVf/kOF+u1wieYnQjWM0fVs7FriBxL3domkQcyJ/V/tflHK8jEXtAALjvWpwtOcuWx4uIeoh0i5nhEXqlXDAtQpI6curiqgcScLrbuV3+4bcKO1aOkpq6YFf/UIOsvucKKEPr6NcwtJjucdTtBN3cVC3Z0efP5F/q1BSAhunMNjVwfdKp4QfyWAsnvNGeFZJ/wI+6fvlHzATN4xYrJst98bbhkhW3OqS9m2cmW0jjODnYbOVBYaFHza2DP67LWerX3RyujJmgARBWUBi+VBS6jycfJRcPCqj9v2fs3E2bjxoM27fs+dc1g/aeSyFBjSVEhHt3Mrb9pu22mjpH7erqEGUxcRtbCv8JZyIuOTW5BzyNdO3Ie9PJ+Epd52nzmQWZ9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
