travis:
  secure:
    BINSTAR_TOKEN: BQhos5qPMQd0kyXVPgm8DyLn1smBHzO9mlENZvp0JAsGMjqpRi0sYkDlhdqCphXK/TSuqU/AD/BVxcLSoMgn4oTHZRH6iyA1ASOeobk+YRkle/Sl3lMHYFws5fodpKlPzGkJ1EK/PfllbdZNvuDgtIy46aLXD8pk0iPxETJt0rNK4xKQ4y8XQRZhxvGVcYoVsak29DKHMYOsofK1pL7oMLqMDhHG7kjE1XfByfKiGsjgjppr1BLtitnc38QRNb9gQ6WdDf5m0QBTEIciBh3JM+Yw0bR9LlnyUo4lgU1SOCo/Jb+rkf9gOqVTkJnbwmlmUUTZjwuwp80eEA1wzVq31KrQ4cS4p/YtLvaVxAO/U2fzyLX5yZyA1rLVTwhWqxgs3/bc7hljWnKrEhCPpK+Yj/Vr66wOkQpchB2cxC1EEnwibfa8kCZC7A3mgmfUsY1bTkFE+20Y9z4yXkdhM0kVSAnWnUTYDTsWWrGv3aGWitVzqmh4KOVuXmfs5PCghcVxf81VsnxHK0cBLqrEZ/AkDN+hq/BUeEKxTYCwuCrBlk2dzBlW9K5DXGd+k7M3IWlWTxCIgBiNrMfDze91m0WX9dJcoXA5zU38QjpwVklBjp3Ii2i2VrfeCduWtLi07H1p3yUWXClRfOBsTeNE7CPK0KI4639aZlboSQFPKR2I5ps=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
