travis:
  secure:
    BINSTAR_TOKEN: CAIko5sxtv9wnlv+j/mof5JsWVCyaKji9jnQhHl6al407gskT8+nC5XEBY/Fd/lo3ogWJT7nk+HzpYjKyjQrL38BKPNLHElvacUJGMKsgPoGmkdozDMo1sZGpWyW7obeAmvKBfqNGR7aWz4cP+LQ4i78GM06zY5xaIus4nLhHBKptqhbMyLoMk+vSdzZ0tvcq17biWlMdLv3PvA8ATTEEXLPO7dTIOWGqXWwPO9Hg3+RotWhusyMcIo4/XU3YuZbw+4ZutsT/6ItNS9w9gFjRu+6XGtBliCQ81MppoAFmNp+xQ1dHB3e+Hx0Q5QW67NPW90evWC9HVhn3dsdc5BhoVT4KzM9Btiwlacvh/Sx2bbgFytfwJWUhn3LBDLnPENNvPR6+KC4JNb4U768UPdX29tkbIAuJ8jsjzrbrdhBtGTKU8eByO7zBVuUCygLGkUas8imv2sJfVj9GTxcJhbUqApkv5V7LxpjFlEpxAyaZDuTsigz4Qx0VNjMASmQ5PnyJL63KBoDInsH+SBIp8hyXZzMYFD55lcgDtaAW3YKBc9JRg9fDW9/zllYP52KVXcYOyyaWUuYPI1rdW8LAWZPNqEIqlocazlaD5Evk0XLF6RZKdS/1hhOgfgrk5LOJzFfJkcrcVEaK/7BEBdzlkycSTpca1VlsQAfGLgBfTkp0hc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
